### ISSUE TITLE
可以试试NEWIFI3的4.4版本

### ISSUE THREAD

**Issue by ghwrf** [flowlife/Padavan-Build#3]
可以试试NEWIFI3的4.4版本

**Comment by flowlife** [comment]
新3用4.4内核的padavan需要拆除C48电容开启GMAC2，不拆的话wan口不能正常工作

**Comment by ghwrf** [comment]
> 新3用4.4内核的padavan需要拆除C48电容开启GMAC2，不拆的话wan口不能正常工作

这个不会拆除啊，涉及硬件了。还有，为什么一定要拆除了，有什么冲突吗？

**Comment by flowlife** [comment]
因为新3的主板设计没有开启GMAC2，需要拆电容来开启。而4.4内核的源码默认是开了GMAC2的，所以不拆除掉C48电容没办法用

**Comment by flowlife** [comment]
> 因为新3的主板设计没有开启GMAC2，需要拆电容来开启。而4.4内核的源码默认是开了GMAC2的，所以不拆除掉C48电容没办法用



> 因为新3的主板设计没有开启GMAC2，需要拆电容来开启。而4.4内核的源码默认是开了GMAC2的，所以不拆除掉C48电容没办法用

**Comment by ghwrf** [comment]
感谢，已经成功，直接指甲钳剪掉。
